### ISSUE TITLE
Unable to run this command in a different directory

### ISSUE THREAD

**Issue by MatteoGioioso** [youyo/aws-sam-action#1]
As I cannot use `uses` with `working-directory`, I am unable to build if my `template.yaml` is stored into a different directory than `github/workspace/`

I have tried this:

```
      - working-directory: ${{env.working-directory}}
        run: echo ""
      - name: sam build
        uses: youyo/aws-sam-action/python3.8@master
        with:
          sam_command: build
```

but of course is failing: `Error: Template file not found at /github/workspace/template.yml`

Do you have any workaround for this?

Thanks

**Comment by MatteoGioioso** [comment]
Sorry my bad. I could just do like this: 

```
      - name: sam build
        uses: youyo/aws-sam-action/python3.8@master
        with:
          sam_command: build -t ./my-path/template.yaml
```
