### ISSUE TITLE
Run on  custom working-directory 

### ISSUE THREAD

**Issue by jcaviedesc** [youyo/aws-sam-action#9]
Hi!

Iam trying run your action on specific folder but get this error `Error: Template file not found at /github/workspace/template.yml`

my folder struct
```bash
├ .github
│  ├─ worklow
│  │   ├─ my-workflow.yaml
├ function
│  ├─template.yml
```
how to set workspace path?

**Comment by youyo** [comment]
How about using the `--template-file` option?
```
      - name: sam deploy
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: 'deploy --template-file function/template.yml'
```
